import './globals.css'
// import { Rajdhani } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

// const rajdhani = Rajdhani({ subsets: ['latin'],weight: ['400','500','600','700'] })

export const metadata = {
  title: 'Sohoz Leaning | A online learning platform',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
      style={{ fontFamily:"sans-serif" }}
      // className={rajdhani.className}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
