import './globals.css'
import { Rajdhani } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import AuthProvider from './context'
import { authOptions } from './api/auth/[...nextauth]/route'
import { getServerSession } from "next-auth/next"

const rajdhani = Rajdhani({ subsets: ['latin'], weight: ['400', '500', '600', '700'] })

export const metadata = {
  title: 'Sohoz Leaning | A online learning platform',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <AuthProvider>
      <html lang="en">
        <body className={rajdhani.className}>
          <Navbar session={session} />
          {children}
          <Footer />
        </body>
      </html>
    </AuthProvider>
  )
}
